# Generated by Django 5.0.2 on 2024-03-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='impuesto',
            field=models.CharField(max_length=10),
        ),
    ]
