# Generated by Django 5.0.2 on 2024-03-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_impuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='impuesto',
            field=models.CharField(max_length=100),
        ),
    ]
