# Generated by Django 5.0.2 on 2024-06-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_vendedorgroup_product_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
